name: Compilar Plugin DLL

on:
  push:
    branches: [ "mestre" ]
  pull_request:
    branches: [ "mestre" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore CustomMacroExtension.sln

    - name: Compilar Plugin
      run: dotnet build CustomMacroExtension.sln --configuration Release

    - name: Upload da DLL
      uses: actions/upload-artifact@v4
      with:
        name: Plugin-Daniel-Net8
        path: "**/bin/Release/net8.0-windows7.0/*.dll"
