name: Compilar Plugin Daniel

on:
  push:
    branches: [ "mestre" ]
  pull_request:
    branches: [ "mestre" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore CustomMacroPlugin1/CustomMacroPlugin1.csproj

    - name: Compilar apenas o Plugin 1
      run: dotnet build CustomMacroPlugin1/CustomMacroPlugin1.csproj --configuration Release --output ./output-dll

    - name: Upload da DLL (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: Plugin-Daniel-Net8
        path: "./output-dll/CustomMacroPlugin1.dll"
